### ISSUE TITLE
Missed link to original repository and LICENSE file

### ISSUE THREAD

**Issue by UnkwUsr** [Hhk78/goldsrc-hack-cstrike#1]
Hello. I see you partially reuploaded mine repository ([hlhax](https://github.com/UnkwUsr/hlhax)) with translated README.md. While translating into different languages is good thing, you're missed [LICENSE](https://github.com/UnkwUsr/hlhax/blob/master/LICENSE) file from the original repository (which is as for now considered illegal). Also following [LICENSE](https://github.com/UnkwUsr/hlhax/blob/master/LICENSE) terms you must leave link to the original repository ([hlhax](https://github.com/UnkwUsr/hlhax)) in some visible place (most likely in README.md).

**Comment by UnkwUsr** [comment]
I see you added credits in https://github.com/Hhk78/goldsrc-multihack-for-linux/commit/b0359b605319ec9158e0db18b4c0d959af0b4c18. Thanks! Closing now.

**Comment by Hhk78** [comment]
i added it when you said. i forgot to write a reply, sorry. thank you for everything!
I hope the recent problem will be solved as soon as possible 
i had to install windows to cheat. :(

(am using yandex translate)
